on:
  workflow_dispatch:
  pull_request_target:
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  merge-dependabot:
    name: Auto-merge Dependabot PRs
    if: "github.event.name == 'pull_request_target' && github.actor == 'dependabot[bot]'"
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
